version: '3.8'

services:
  as:
    build:
      context: ./AS
    image: as-app
    container_name: as-container
    ports:
      - "53533:53533/udp"
    networks:
      - dns-net

  fs:
    build:
      context: ./FS
    image: fs-app
    container_name: fs-container
    ports:
      - "9090:9090"
    depends_on:
      - as
    networks:
      - dns-net

  us:
    build:
      context: ./US
    image: us-app
    container_name: us-container
    ports:
      - "8080:8080"
    depends_on:
      - fs
      - as
    networks:
      - dns-net

networks:
  dns-net:
    driver: bridge
